#!/usr/bin/env bash
set -euo pipefail

# One-shot migration helper for machines that bootstrapped initd before the
# three-bucket restructure (everything used to live at the repo root in
# fish/, git/, ghostty/, kitty/, mise/, nvim/, tmux/).
#
# It moves machine-local gitignored files from the old flat paths into the new
# shared/configs/ paths. After running this, re-run bootstrap.sh to refresh the
# managed symlinks.
#
# Safe to re-run. Each step is a no-op if the source doesn't exist or the
# destination is already populated.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

# shellcheck disable=SC1091
source "${ROOT_DIR}/shared/lib/logging.sh"

moved=0
skipped=0

# Move src → dst when src exists and dst does not. The path arguments are
# repo-relative because cd "${ROOT_DIR}" runs at the top of the script.
migrate_path() {
  local src="$1" dst="$2"

  if [[ ! -e "${src}" && ! -L "${src}" ]]; then
    return
  fi

  if [[ -e "${dst}" || -L "${dst}" ]]; then
    log_warn "Skipping ${src}: ${dst} already exists."
    skipped=$((skipped + 1))
    return
  fi

  mkdir -p "$(dirname "${dst}")"
  mv "${src}" "${dst}"
  log_success "Migrated ${src} -> ${dst}"
  moved=$((moved + 1))
}

main() {
  log "Migrating machine-local files from the old flat layout..."

  # Gitignored files git pull won't have moved for you.
  migrate_path "git/local.gitconfig"                       "shared/configs/git/local.gitconfig"
  migrate_path "fish/.config/fish/local.fish"              "shared/configs/fish/.config/fish/local.fish"
  migrate_path "fish/.config/fish/conf.d/local.fish"       "shared/configs/fish/.config/fish/conf.d/local.fish"
  migrate_path "fish/.config/fish/fish_variables"          "shared/configs/fish/.config/fish/fish_variables"
  migrate_path "fish/.config/fish/functions"               "shared/configs/fish/.config/fish/functions"
  migrate_path "fish/.config/fish/completions"             "shared/configs/fish/.config/fish/completions"

  # Generated by lazy.nvim. It will recreate this on first launch, so drop it
  # instead of moving it.
  if [[ -d "nvim/.config/nvim/plugin" ]]; then
    rm -rf "nvim/.config/nvim/plugin"
    log_success "Removed stale nvim/.config/nvim/plugin/ (lazy.nvim regenerates it)."
  fi

  # Sweep up old top-level directories. -depth makes find delete leaves first,
  # which is what lets the parent dirs become empty and get pruned too.
  local old_dir removed_dirs=0
  for old_dir in fish git ghostty kitty mise nvim tmux; do
    [[ -d "${old_dir}" ]] || continue

    # If anything other than empty dirs remains, leave the tree alone — it could
    # be user state we don't know about.
    if [[ -n "$(find "${old_dir}" \( -type f -o -type l \) -print -quit 2>/dev/null)" ]]; then
      log_warn "Leaving ${old_dir}/ in place — still contains files or symlinks."
      continue
    fi

    find "${old_dir}" -depth -type d -empty -delete 2>/dev/null || true
    if [[ ! -d "${old_dir}" ]]; then
      log_success "Removed empty ${old_dir}/"
      removed_dirs=$((removed_dirs + 1))
    fi
  done

  echo
  log_info "Moved: ${moved}, skipped (already migrated): ${skipped}, empty dirs removed: ${removed_dirs}"

  if [[ ${moved} -eq 0 && ${removed_dirs} -eq 0 && ${skipped} -eq 0 ]]; then
    log_success "Nothing to migrate — looks like this machine is already on the new layout."
    return
  fi

  log_success "Migration complete."
  log_info "Now run: bash bootstrap.sh   (re-links symlinks to the new shared/configs/ paths)"
}

main "$@"
