# Tokyo Night
[colors]
bg       = #00000000
bg-alt   = #00000000
fg       = #c0caf5
fg-dim   = #565f89
blue     = #7aa2f7
blue-alt = #bb9af7
red      = #f7768e
green    = #9ece6a
yellow   = #e0af68
orange   = #ff9e64

[bar/main]
monitor               =
width                 = 100%
height                = 46
dpi                   = 96
background            = ${colors.bg}
foreground            = ${colors.fg}
line-size             = 2
border-size           = 0
padding-left          = 2
padding-right         = 2
module-margin-right   = 1
font-0                = FiraCode Nerd Font Mono:style=Bold:size=22;6
font-1                = FiraCode Nerd Font Mono:size=15;5
font-2                = FiraCode Nerd Font Mono:style=Bold:size=21;6
modules-left          = workspaces
modules-center        =
modules-right         = pulseaudio backlight battery wlan cpu memory tray date
wm-restack            = i3
override-redirect     = false
cursor-click          = pointer
cursor-scroll         = ns-resize
enable-ipc            = true

[module/workspaces]
type     = custom/script
exec     = ~/.config/polybar/workspaces.sh
tail     = true

[module/date]
type     = internal/date
interval = 5
date     = %a %d %b
time     = %H:%M
label    =  %date% %time%

[module/pulseaudio]
type                   = internal/pulseaudio
use-ui-max             = false
format-volume          = <ramp-volume> <label-volume>
label-volume           = %percentage%%
label-muted            = 󰝟 muted
label-muted-foreground = ${colors.fg-dim}
ramp-volume-0          = 󰕿
ramp-volume-1          = 󰖀
ramp-volume-2          = 󰕾
ramp-volume-foreground = ${colors.blue}

[module/backlight]
type                  = internal/backlight
card                  = intel_backlight
use-actual-brightness = true
enable-scroll         = true
format                = <ramp> <label>
label                 = %percentage%%
ramp-0                = 󰃞
ramp-1                = 󰃟
ramp-2                = 󰃠
ramp-foreground       = ${colors.blue}

[module/wlan]
type                          = internal/network
interface                     = wlp85s0f0
interval                      = 5
label-connected               = 󰤨 %essid%
label-disconnected            = 󰤭 --
label-disconnected-foreground = ${colors.fg-dim}

[module/battery]
type                          = internal/battery
battery                       = BAT1
adapter                       = AC
full-at                       = 99
low-at                        = 10
poll-interval                 = 10
format-charging               = <animation-charging> <label-charging>
format-discharging            = <ramp-capacity> <label-discharging>
format-full                   = <label-full>
format-low                    = <ramp-capacity> <label-low>
label-charging                = %percentage%%
label-discharging             = %percentage%%
label-full                    = 󰁹 Full
label-low                     = %percentage%%
label-low-foreground          = ${colors.red}
ramp-capacity-0               = 󰂎
ramp-capacity-1               = 󰁺
ramp-capacity-2               = 󰁾
ramp-capacity-3               = 󰂀
ramp-capacity-4               = 󰁹
ramp-capacity-foreground      = ${colors.blue}
animation-charging-0          = 󰢜
animation-charging-1          = 󰂆
animation-charging-2          = 󰂈
animation-charging-3          = 󰂊
animation-charging-4          = 󰂅
animation-charging-foreground = ${colors.green}
animation-charging-framerate  = 750

[module/cpu]
type                     = internal/cpu
interval                 = 2
format-prefix            = "󰍛 "
format-prefix-foreground = ${colors.blue}
label                    = %percentage:2%%

[module/memory]
type                     = internal/memory
interval                 = 3
format-prefix            = "󰾆 "
format-prefix-foreground = ${colors.blue}
label                    = %percentage_used:2%%

[module/tray]
type         = internal/tray
tray-padding = 6px
tray-maxsize = 16
