-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BNQ BenQ RD320U V9R01600019",
  mode = "3840x2160@60.00",
  position = "0x-1728",
  scale = 1.06667,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Display 0x0804",
  mode = "2560x1600@120.00",
  position = "376x0",
  scale = 1.33333,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
