-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:LG Display 0x0804",
  mode = "2560x1600@120.00",
  position = "2300x1160",
  scale = 1.33333,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:XXX Beyond TV 0x00010000",
  mode = "1920x1080@60.00",
  position = "1920x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
